---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-deployment
spec:
  selector:
    matchLabels:
      app: bank
  replicas: 1
  template:
    metadata:
      labels:
        app: bank
    spec:
      containers:
        - name: bank
          image: leonahoms/bank
          ports:
            - containerPort: 9092
          env:   # Setting Environmental Variables
            - name: DB_HOST   # Setting Database host address
              value: bankdb
            - name: DB_NAME  # Setting Database name
              value: bank
            - name: DB_USERNAME  # Setting Database username
              value: root
            - name: DB_PASSWORD # Setting Database password
              value: root
---
# Define a 'Service' To Expose the application
apiVersion: v1
kind: Service
metadata:
  name: bank-service
spec:
  ports:
    - protocol: "TCP"
      port: 9092    # Port inside the cluster
      targetPort: 9092   # Port exposed to the outside
  selector:
    app: bank
  type: ClusterIP