---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-deployment
spec:
  selector:
    matchLabels:
      app: payment
  replicas: 1
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
        - name: payment
          image: leonahoms/payment
          ports:
            - containerPort: 9094

---
# Define a 'Service' To Expose the application
apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  ports:
    - protocol: "TCP"
      port: 9094    # Port inside the cluster
      targetPort: 9094   # Port exposed to the outside
  selector:
    app: payment
  type: ClusterIP