---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: paypal-deployment
spec:
  selector:
    matchLabels:
      app: paypal
  replicas: 1
  template:
    metadata:
      labels:
        app: paypal
    spec:
      containers:
        - name: paypal
          image: leonahoms/paypal
          ports:
            - containerPort: 9096
          env:   # Setting Environmental Variables
            - name: DB_HOST   # Setting Database host address
              value: mysql
            - name: DB_NAME  # Setting Database name
              value: paypal
            - name: DB_USERNAME  # Setting Database username
              value: root
            - name: DB_PASSWORD # Setting Database password
              value: root
---
# Define a 'Service' To Expose the application
apiVersion: v1
kind: Service
metadata:
  name: paypal-service
spec:
  ports:
    - protocol: "TCP"
      port: 9096    # Port inside the cluster
      targetPort: 9096   # Port exposed to the outside
  selector:
    app: paypal
  type: NodePort