---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-deployment
spec:
  selector:
    matchLabels:
      app: stock
  replicas: 1
  template:
    metadata:
      labels:
        app: stock
    spec:
      containers:
        - name: stock
          image: leonahoms/stock
          ports:
            - containerPort: 9097
          env:   # Setting Environmental Variables
            - name: DB_HOST   # Setting Database host address
              value: stockdb
            - name: DB_NAME  # Setting Database name
              value: stock
            - name: DB_USERNAME  # Setting Database username
              value: root
            - name: DB_PASSWORD # Setting Database password
              value: root
---
# Define a 'Service' To Expose the application
apiVersion: v1
kind: Service
metadata:
  name: stock-service
spec:
  ports:
    - protocol: "TCP"
      port: 9097    # Port inside the cluster
      targetPort: 9097   # Port exposed to the outside
  selector:
    app: stock
  type: ClusterIP