server:
  port: 9090
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: account-service
          uri: lb://account-service
          predicates:
              - Path=/accounts/**
          filters:
            - AuthenticationFilter

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/orders/**
          filters:
            - AuthenticationFilter

        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/products/**
          filters:
            - AuthenticationFilter
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9000/eureka/
    instance:
      hostname: localhost
logging:
  level:
    '[org.springframework.cloud.gateway]': TRACE
jwt:
  secret: testing
  validity: 20
  authDisabled: true
#        - id: ORDER-SERVICE
#          uri:
#            lb://ORDER-SERVICE
#          predicates:
#            - Path=/orders/**
#          filters:
#            - name: CircuitBreaker
#              args:
#                name: ORDER-SERVICE
#                fallbackUri: forward:/orderServiceFallBack
#        - id: PRODUCT-SERVICE
#          uri:
#            lb://PRODUCT-SERVICE
#          predicates:
#            - Path=/products/**
#          filters:
#            - name: CircuitBreaker
#              args:
#                name: PRODUCT-SERVICE
#                fallbackUri: forward:/productServiceFallBack