
server:
  port: 9090
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: account-service
          uri: http://account-service:9091
          predicates:
            - Path=/accounts/**
          filters:
            - AuthenticationFilter

        - id: order-service
          uri: http://order-service:9093
          predicates:
            - Path=/orders/**
          filters:
            - AuthenticationFilter

        - id: product-service
          uri: http://product-service:9096
          predicates:
            - Path=/products/**
          filters:
            - AuthenticationFilter
jwt:
  secret: tokensecret
  validity: 20
  authDisabled: true